import Head from "next/head";

import Navbar from "../components/Navbar";

import DividerList from "../components/DividerList";

import HeroFifure from "../components/HeroFigure";

//홈페이지에 전해줄 데이터 여기에

const HomeItem = [
  {
    id: 'home',
    bag: "/bag/home.png",
    logo: "/logo/cardio.png",
    title: '당신의 오늘 하루, 건강계획을 세워보세요.',
    desc: '체력평가부터 개인맞춤운동까지!',
  },
  {
    id: 'cardio',
    bag: "/bag/cardio.png",
    logo: "/logo/cardio.png",
    title: '심장질환자 또는 심혈관계 고위험군대상 심혈관계 피트니스 증진 서비스',
    desc: '',
  },
  {
    id: 'harufit',
    bag: "/bag/harufit.png",
    logo: "/logo/harufit.png",
    title: '심장재활전용 디지털 헬스케어 서비스',
    desc: '웹캠으로 분석한 개인별 체력평가를 바탕으로 맞춤형 운동법을 알려줘요',
  },
  {
    id: 'refresh',
    bag: "/bag/refresh.png",
    logo: "/logo/refresh.png",
    title: '지쳤던 나를 위한 시간',
    desc: '체계적인 명상·요가프로그램을 통한 몸 마음 힐링 서비스',
  }
]



export default function Home() {
  return (

    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />

      <DividerList homeItem={HomeItem} />
      <HeroFifure />

    </div>
  );
}
